spring:
  application:
    name:
      homework-3-spring-boot
application:
  minimal-correct-answer-count: 2
  locale: ru_RU
  file-name-by-locale:
    ru_RU: questions_ru.csv
    en_EN: questions.csv
