spring:
  application:
    name: homework-5-jdbc
  shell:
    script:
      enabled: true
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  liquibase:
    change-log: db_change_logs/master.xml
